# Generated by Django 5.2.1 on 2025-09-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
