# Generated by Django 5.2.1 on 2025-09-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjj', '0002_video_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='CloudFront URL to the thumbnail image (public bucket)', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(help_text='CloudFront or S3 URL to the video file (private bucket)'),
        ),
    ]
