# Generated by Django 5.2.1 on 2025-06-05 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjj', '0003_guard_position_technique_remove_video_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bjj.guard')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bjj.position')),
                ('tags', models.ManyToManyField(blank=True, to='bjj.tag')),
                ('technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bjj.technique')),
            ],
        ),
    ]
