# Generated by Django 5.2.1 on 2025-06-06 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bjj', '0004_tag_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guard',
            old_name='name',
            new_name='guard_name',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='name',
            new_name='position_name',
        ),
        migrations.RenameField(
            model_name='technique',
            old_name='name',
            new_name='technique_name',
        ),
    ]
