# Generated by Django 5.2.1 on 2025-06-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjj', '0005_rename_name_guard_guard_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guard',
            old_name='guard_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='position_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='technique',
            old_name='technique_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
