# Generated by Django 5.2.1 on 2025-06-17 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjj', '0006_rename_guard_name_guard_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.TextField(default=django.utils.timezone.now, help_text='Comma-separated or space-separated tags like: arm_bar, prof_ali, no_gi'),
            preserve_default=False,
        ),
    ]
