name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env.dev file
        run: |
          mkdir -p Jiujitsuteria
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > Jiujitsuteria/.env.dev
          echo "DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }}" >> Jiujitsuteria/.env.dev
          echo "DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}" >> Jiujitsuteria/.env.dev
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> Jiujitsuteria/.env.dev

      - name: Run Django tests
        run: |
          python3 manage.py test --settings=jiujitsuteria.settings.dev

