name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      # 4. Run Django tests
      - name: Run Django tests
        run: |
          python3 manage.py test --settings=jiujitsuteria.settings.dev

  # Deployment (runs only if tests pass)
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      # 1. Checkout (not strictly needed for SSH, but useful for logs)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. SSH into EC2 and run deploy.sh in DRY RUN mode
      - name: Deploy to EC2 (Dry Run)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: deploy
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/deploy/bjj_app/scripts
            ./deploy.sh --dry-run

